### ISSUE TITLE
Reduce MultiSig timelock on testnets

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/staked-celo#49]
Config had granularity on order of number of days for specifying timelock. Not great for manual testing/debugging. Let's make it on the order of a few minutes.

**Comment by pahor167** [comment]
Alfajores multisig proxy: 0xf68665Ad492065d7d6f2ea26d180f86A585455Ab

New implementation: 0x395252a53A657D82A5B4A035BBcb44bA71A9404d

**Comment by pahor167** [comment]
const multisig: MultiSig = await hre.ethers.getContract("MultiSig");

const multisigProxyAddress = "0xf68665Ad492065d7d6f2ea26d180f86A585455Ab"
const newImplementation = "0x395252a53A657D82A5B4A035BBcb44bA71A9404d"

const upgradeEncoded = multisig.interface.encodeFunctionData("upgradeTo", [newImplementation]);
await executeAndWait(multisig.attach(multisigProxyAddress).submitProposal([multisigProxyAddress], [0], [upgradeEncoded]))
