### ISSUE TITLE
Set up new alfajores deployment

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/staked-celo#63]
Update web-app, backend, docs.

Forum post, notify partners we're aware of.

**Comment by pahor167** [comment]
Multisig: 0x05a56F52617Ff8444D460C7DeBE3D02fED8Df01D
Manager: 0x0901f312e46951785af12BC52A321AFF6320689a
Account: 0xBa23e91C863a34f6E80A9718b8bB6aD4a2688D18
StakedCelo: 0xdbD7426514e0E5a42Bb2561DE289b87ecaC0f450
RebaseStakedCelo: 0x50Bf8C7F089Bf3387aC85563843acC510778Cb2d
